# Generated by Django 4.0.6 on 2022-07-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayer',
            options={'ordering': ['answered', '-priority', '-updated', '-created']},
        ),
    ]
